### ISSUE TITLE
Rendering error in sword blocking (Legacy animation)

### ISSUE THREAD

**Issue by jahirtrap** [Fuzss/goldenagecombat#1]
![2021-05-07_23 33 53](https://user-images.githubusercontent.com/75038202/117526885-9e899b80-af8d-11eb-801e-9af3ed506ab1.png)
![2021-05-07_23 34 04](https://user-images.githubusercontent.com/75038202/117526889-a1848c00-af8d-11eb-9add-2ee9f6a33bd1.png)

Mod version: 1.5.1-1.16.5 & 1.5.2-1.16.5
Config: "Old Blocking Pose" = true

**Comment by AnonymoCraft** [comment]
Exact same bug for me

**Comment by Dreepye** [comment]
Patch : in BlockingHeldItemLayer remove all matrixStackIn.scale and reajust the position when sword blocking with matrixStackIn.translate

**Comment by Fuzss** [comment]
Fixed in v.1.5.3.


> Patch : in BlockingHeldItemLayer remove all matrixStackIn.scale and reajust the position when sword blocking with matrixStackIn.translate

Thanks, scaling itself is fine, just had a single negative scale in there which was the issue.
