### ISSUE TITLE
[1.18.2] No sound on attacking mobs.

### ISSUE THREAD

**Issue by Baggytrousers27** [Fuzss/goldenagecombat#10]
There is no impact sound when an attack connects with a mob. Dunno if it's supposed to be that way but it feels somehow wrong.

Forge 40.0.25
PuzzlesLib-v3.3.2-1.18.2-Forge
GoldenAgeCombat-v3.3.0-1.18.2-Forge

**Comment by Fuzss** [comment]
This is intended. Minecraft has a bunch of different sounds that play depending on the strength/type of attack, but they only really make sense in a cooldown based system. When fast clicking is allowed, which this mod does, you'll just be spammed with attack sounds, therefore I've disabled all of them by default.

To change that, remove some of the entries in the `canceled_attack_sounds` config options in the `classic_combat` config category.
