### ISSUE TITLE
Attack reach not working properly.

### ISSUE THREAD

**Issue by JohnSmith474** [Fuzss/goldenagecombat#14]
The attack reach attribute seems to be working only when in creative mode. I was wondering, where exactly in the source is the implementation of the attack reach attribute in the first place?

**Comment by Fuzss** [comment]
Implementation is [here](https://github.com/Fuzss/goldenagecombat/blob/434bf56a2dfd411ae9734fc415f133ab011e016e/src/main/java/fuzs/goldenagecombat/mixin/client/GameRendererMixin.java#L79) and above that.

It's working fine, the reach is simply greater in creative. CTS work like that, too (although they use different values).
