### ISSUE TITLE
Issue with Useless sword.

### ISSUE THREAD

**Issue by KotoriTakamiya** [Fuzss/goldenagecombat#15]
Afternoon! I found an issue while using Useless sword mod.

You know, Useless sword has an ability attached to it. and it happens if you right-click with the sword.

and it doesn't work, we all know why. It has been temp. fixed if I equip my off-hand with a shield, since the shield would take away the "sword block"

My question is: Is there a way to keep the sword block, but still manage to activate the ability from the useless sword mod?

I messaged the author of the Useless mod too, hoping the "right-click" could be binded in a near future!

thankies!

**Comment by Fuzss** [comment]
No, that's not possible and I'm not planning on adding support. It's like with shields; when there is a dedicated right-click action available sword blocking will be skipped. But yes, maybe the mod dev can come up with a different way for activating their ability.
