### ISSUE TITLE
crashes when opening

### ISSUE THREAD

**Issue by hclaim0** [Fuzss/goldenagecombat#19]
goldenage combat crashes when loading, .minecraft file works fine on different PC.

[latest (6).log](https://github.com/Fuzss/goldenagecombat/files/9712714/latest.6.log)

**Comment by Fuzss** [comment]
Looks like you're using the 1.18.1 version on 1.18.2.

**Comment by hclaim0** [comment]
it is the 1.18.2 version, also it works fine on another (linux) computer that is running 1.18.2

**Comment by Fuzss** [comment]
The version listed as latest on Curse is the 1.18.1 version unfortunately. The missing method referenced in the log does indeed only come up in the 1.18.1 version, so you must have accidentally downloaded that version.

Can you just try again with the original PC using this version? https://www.curseforge.com/minecraft/mc-mods/golden-age-combat/files/3671444
