### ISSUE TITLE
ISSUE WITH SILIENT GEAR MOD

### ISSUE THREAD

**Issue by RAFAERU-SAN** [Fuzss/goldenagecombat#20]
Hello, I tested this mod with slient gear and found a conflict. when i make slient gear weapons, this mod automatically lowers the sword's total damage. can you make these two mods compatible?

I'll put some prints that demonstrate the conflict between the mods:

![2023-01-16_18 12 31](https://user-images.githubusercontent.com/98791086/212758802-5b064b1b-55cc-4de4-9d39-8ee315b95b0a.png)

here it demonstrates that the sword does 13 damage, but in reality it does 53 as shown in the next image:

![2023-01-16_18 12 35](https://user-images.githubusercontent.com/98791086/212758984-1dc9fd44-ce45-4818-aec3-57e9b72af0d7.png)

![2023-01-16_18 12 47](https://user-images.githubusercontent.com/98791086/212759142-ec8dc6e5-7eea-4dd0-90e5-0553458922c7.png)

**Comment by Fuzss** [comment]
What MC version are you playing?

**Comment by RAFAERU-SAN** [comment]
1.16.5 forge 36.2.39

**Comment by Fuzss** [comment]
You can add the Silent Gear weapons to the `goldenagecombat: attack_damage_blacklist` item tag. Alternatively just disable the `Legacy Attack Damage` option in the common config.

**Comment by RAFAERU-SAN** [comment]
Thank you man!
