### ISSUE TITLE
Struggling to understand the Blocking function support

### ISSUE THREAD

**Issue by Firespecialstar** [Fuzss/goldenagecombat#22]
Hello, i will very probably sound very dumb, but i'm struggling to understand the Q&A in regards of the sword blocking inclusion/exclusion function. i understood that i have to include goldenagecombat:sword_blocking_inclusions/exclusions in an item tag, but i did not understand where to use the function. it's not present in the defaults commands of minecraft and it's not present in the config files. can u do a better explanation in regards of this function? (I don't play actively modern versions, and i never met this item tag function anywhere either)
using the 1.16.5 version of the mod, trying to add the blocking function to the tetra swords mod

**Comment by Fuzss** [comment]
Item tags are a vanilla Minecraft feature. They are provided via data packs which are applied per world. There is no global config directory for those. You can read more about [data packs](https://minecraft.fandom.com/wiki/Data_pack) and [item tags](https://minecraft.fandom.com/wiki/Tag#Java_Edition) on the Minecraft Wiki.

I'm aware this is highly inconvenient for a normal user like you, but unfortunately is the approach Minecraft itself has taken for customization.

**Comment by Fuzss** [comment]
If you have any more questions / issues I recommend joining our [Discord server](https://lunapixel.studio/discord), there are people there that can help you.

**Comment by Firespecialstar** [comment]
thanks for the infos, i knew it was the right idea asking here.
