### ISSUE TITLE
[Bug]: 1.20 Port does not include blockhitting

### ISSUE THREAD

**Issue by WyattTheSkid** [Fuzss/goldenagecombat#23]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

GoldenAgeCombat-v8.0.0-1.20.1-Forge

### Notes (Required)

Saw the 1,20 port and downloaded it. Realized I can't block with my sword. Saw on the curse page that sword blocking has been moved to a separate mod. Clicking the link for "Sword Blocking Mechanics" takes me to something called diagonal fences.

Screenshot: https://gyazo.com/b9327e6da2252ab92a828dd74b9c1230

**Comment by OysterStew** [comment]
Downloaded this specifically for no cooldown and sword blocking. Ran into the same problem with the link.

**Comment by WyattTheSkid** [comment]
fuzs sent me it on discord https://cdn.discordapp.com/attachments/917550806922846299/1170134603131015229/SwordBlockingMechanics-v8.0.0.542-1.20.1-Forge.jar?ex=6557efc5&is=65457ac5&hm=ecfecdf4e669992ad0cdc65203ea56f8fa1f845ab9c65e4fba8a49c022dcea42&

**Comment by WyattTheSkid** [comment]
> Downloaded this specifically for no cooldown and sword blocking. Ran into the same problem with the link.

https://cdn.discordapp.com/attachments/917550806922846299/1170134603131015229/SwordBlockingMechanics-v8.0.0.542-1.20.1-Forge.jar?ex=6557efc5&is=65457ac5&hm=ecfecdf4e669992ad0cdc65203ea56f8fa1f845ab9c65e4fba8a49c022dcea42&
