### ISSUE TITLE
[Crash]: The custom attack damage overrides function causes a crash.

### ISSUE THREAD

**Issue by FitchKrause** [Fuzss/goldenagecombat#25]
### Mod Loader (Required)

Quilt/Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.0

### Notes (Required)

1. In the mod menu, select this mod;
2. Open the "Server Configurations", select the world and click on "Create & Edit Config";
3. Open "Attributes" and select "Custom Attack Damage Overrides";
4. In the "Edit String List" we add one of the following text options, instead of a diamond sword, you can enter any object, this does not affect the result in any way:
    minecraft:diamond_sword,10.0;
    minecraft:diamond_sword,10,0;
    diamond_sword,10.0;
    diamond_sword,10,0;
5. Congratulations! You have achieved a crash! And it works on both Quilt and Fabric.

### Crash Report (Required)

https://gist.github.com/FitchKrause/9940d925524b88f3626b604002a018f6

**Comment by Fuzss** [comment]
Fixed in v8.0.1.
