### ISSUE TITLE
[Crash]: Weird incompatibility between Golden Age Combat and Puzzle Libs latest version (MC 1.18.2)

### ISSUE THREAD

**Issue by Yokisan249** [Fuzss/goldenagecombat#26]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.18.2

### Mod Version (Required)

3.4.1

### Notes (Required)

Golden Age Combat 3.4.1 and Puzzle Libs 3.5.8 just hate each other. When booting up minecraft nothing happens but when you create a new world, the game crashes when world generation reaches 100%. All it says is: The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Cannot read field "f_19853_" because the return value of "net.minecraftforge.event.entity.PlaySoundAtEntityEvent.getEntity()" is null.

### Crash Report (Required)

https://gist.github.com/Yokisan249/972197c302e7a06cd49106012aa0acf8

### latest.log (Optional)

https://gist.github.com/Yokisan249/de9367628381b7d4dc4706858216cd53

**Comment by Fuzss** [comment]
Fixed in latest Puzzles Lib for 1.18.2.
