### ISSUE TITLE
[Bug]: Brush Item Use Animation Broken

### ISSUE THREAD

**Issue by marianyp** [Fuzss/goldenagecombat#27]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.1

### Notes (Required)

The animation for the [Brush Item](https://minecraft.wiki/w/Brush) is broken. When right-clicking with the brush, typically the "sweeping" animation plays. However, with this mod, it seems to break the animation and zooms into the brush texture.

**Comment by Fuzss** [comment]
Fixed in v8.0.2.
