### ISSUE TITLE
[Crash]: On Open Inventory when using Regions Unexplored

### ISSUE THREAD

**Issue by Sarund9** [Fuzss/goldenagecombat#29]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.0.1

### Notes (Required)

Install Golden Age Combat, and Regions Unexplored.
Crash happens when opening the Inventory Screen.

### Crash Report (Required)

https://gist.github.com/Sarund9/6b04bbf0d670be0fcd82d1881368632b

**Comment by Fuzss** [comment]
Fixed in v8.0.2.
