### ISSUE TITLE
[Suggestion]: Shrink item frame hitboxes to regular size

### ISSUE THREAD

**Issue by QueNerguy** [Fuzss/goldenagecombat#30]
### Mod Loader (Optional)

Quilt

### Minecraft Version(s) (Optional)

1.20.4

### Mod Version(s) (Optional)

v20.4.2

### Suggestion (Required)

One of the features of this mod is that it enlarges hitboxes by 10%, which is nice for combat, but super annoying when trying to open barrels or chests with an item frame placed on them, because you just end up rotating the item in the frame rather than opening the chest, over and over. Would it be possible to keep that hitbox the original size?

**Comment by Fuzss** [comment]
Fixed in latest supported versions, thanks! 1.20.4 has been dropped in favor of the upcoming 1.21 port though.
