### ISSUE TITLE
[Suggestion]: Disable certain features when joining servers that don't have GAC

### ISSUE THREAD

**Issue by DBTDerpbox** [Fuzss/goldenagecombat#33]
### Mod Loader (Optional)

Fabric

### Minecraft Version(s) (Optional)

1.20.4

### Mod Version(s) (Optional)

20.4.2

### Suggestion (Required)

Golden Age Combat should disable some of its features when joining servers that don't have it installed, mainly the 10% hitbox increase as this would just be cheating and could lead to players getting banned on PVP servers.

I haven't done a deep look into what could be considered cheating, but I feel like this could be a large problem for people just installing the mod without thinking that they could get banned on PVP servers

Here's a video of me attacking a player with the mod installed on a vanilla server
[Screencast_20240524_232643.webm](https://github.com/Fuzss/goldenagecombat/assets/65347035/d07c23d7-25ed-426c-a790-7e4c0748b91c)

**Comment by minhcrafters** [comment]
Confirmed. I used a modpack called "Re-Console" without knowing the existence of this mod that comes along with it, and got banned on Hypixel.

**Comment by AzaleaCatgirl99** [comment]
> Confirmed. I used a modpack called "Re-Console" without knowing the existence of this mod that comes along with it, and got banned on Hypixel.

Re-Console (and Legacy4J) change too much of the vanilla game, please don't use on big servers like Hypixel. This is not just a GAC issue, but rather a lot of the mods used in Re-Console, and Legacy4J's code.

**Comment by omo50** [comment]
> > Confirmed. I used a modpack called "Re-Console" without knowing the existence of this mod that comes along with it, and got banned on Hypixel.
> 
> Re-Console (and Legacy4J) change too much of the vanilla game, please don't use on big servers like Hypixel. This is not just a GAC issue, but rather a lot of the mods used in Re-Console, and Legacy4J's code.

As the lead dev of Re-Console, most of the things should work fine with servers. The issue comes with options like Hitbox Inflation being turned on in servers without the mod, which acts like a cheat

**Comment by Fuzss** [comment]
Golden Age Combat is not designed to be used on servers without it.
