### ISSUE TITLE
[Bug]: Shield animation

### ISSUE THREAD

**Issue by DanielMC101** [Fuzss/goldenagecombat#38]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21.1 - 1.20.1

### Mod Version(s) (Required)

1.21.1

### Notes (Required)

The shield animation basically plays instantly, not sure if this was intentional or not.

https://github.com/user-attachments/assets/0e031137-60e7-4f93-a3c8-43bbb8299615

### latest.log (Required)

https://gist.github.com/DanielMC101/026c015c3a299a39039aa8ce5c9c06c1

**Comment by Fuzss** [comment]
You can disable the `noReequipWhenUsing` client config option if you want to restore the vanilla animation.
