### ISSUE TITLE
1.12.2 golden age 1.5.2 support 

### ISSUE THREAD

**Issue by ghost** [Fuzss/goldenagecombat#4]
I suggest adding support for the new version of the mod
On 1.12.2
since many people lag or do not start minecraft on 1.16.5
And in general 1.12.2 Will be more stable
And there are many cool mods and servers that are not available on 1.16.5
This mod helps in pvp on servers 1.12.2 on which there is pvp from 1.8 there is no blocking since plugins cannot add blocks
And the Golden Age adds it and is generally more convenient to play

On version golden age 1.2.3
There is a bug when enabling Require Sweeping Edge
Upon hitting the mob, it starts to stop as if the player enters the water
Version 1.5.2 does not have this bug

**Comment by Fuzss** [comment]
Backporting is not an option, too much has changed in between all those versions.

I'm also unable to reproduce the bug you described, if it's serious please provide a video or a series of images and open a separate ticket.
