### ISSUE TITLE
[BUG] rebinding attack and destroy to a mouse button makes it "autoclick" when held down

### ISSUE THREAD

**Issue by WyattTheSkid** [Fuzss/goldenagecombat#7]
Was out of the house away from my pc and wanted to test blockhitting on my laptop so I rebinded the left and right mouse buttons to my g and h keys because its kind of hard to press both mouse buttons at once on a trackpad and I accidentally discovered that while holding down the key the sword would automatically swing. after rebinding it to the left mouse button, the issue did not persist. I have attached a couple of gifs below recreating the bug.

Holding the mouse button down and only let go of it a couple of times to try again but it only attacked as many times as I clicked
[![Image from Gyazo](https://i.gyazo.com/1ffeeee8912f6238fbcaeec9cf026862.gif)](https://gyazo.com/1ffeeee8912f6238fbcaeec9cf026862)

holding my "g" key down with it bound to attack and destroy
[![Image from Gyazo](https://i.gyazo.com/67df57e3433bdb23eb38216cfe68b3a1.gif)](https://gyazo.com/67df57e3433bdb23eb38216cfe68b3a1)

looking to make an hcf server with modern game features except for new pvp because it sucks having a built in autoclicker would definitely ruin the competitive experience. Thanks for your time. (P.S. fabric support would be really cool because of the level of compatibility it has) have a good day

**Comment by Fuzss** [comment]
There is an `Attack While Using` config option, maybe disabling that will help. Otherwise I'm not changing anything in regards to clicking behavior.
I just checked, and this also happens in vanilla for me. Although not at such speed (both with the mod and in vanilla), but that is probably operating system dependent.

**Comment by WyattTheSkid** [comment]
> There is an `Attack While Using` config option, maybe disabling that will help. Otherwise I'm not changing anything in regards to clicking behavior. I just checked, and this also happens in vanilla for me. Although not at such speed (both with the mod and in vanilla), but that is probably operating system dependent.

alright I'll give that a shot, just figured id let you know about this though

**Comment by Fuzss** [comment]
So closing this now since the behavior is vanilla after all and I don't see a reason to change this.
