### ISSUE TITLE
Game crashes when loading a resource pack (1.18.1)

### ISSUE THREAD

**Issue by Seanniex** [Fuzss/goldenagecombat#8]
When ever I load a resource pack the game crashes when Puzzlelib and GoldenAgeCombat is installed. Without the puzzlelib and GoldenAgeCombat loading a resource pack seems to be working fine

**Comment by Fuzss** [comment]
Fixed in v.3.3.0.

**Comment by QuibopWon** [comment]
fix for 1.18.1 plz create hasn't updated to 1.18.2 yet

**Comment by Fuzss** [comment]
Hotfix for 1.18.1 is out.
