### ISSUE TITLE
Two bugs after turning off "Remove Attack Cooldown"

### ISSUE THREAD

**Issue by XM666-Dev** [Fuzss/goldenagecombat#9]
"Air Sweep Attack" and "Continuous Air Sweeping" don't work!
It's not my fault, I didn't use other mods
My English is not good so this is machine translation

**Comment by Fuzss** [comment]
I have to admit the "Remove Attack Cooldown" was only slapped on there, I never intended the mod to support keeping the attack cooldown in any way originally. It's possible those other features are indeed affected. I'll look into it for 1.19.

**Comment by Fuzss** [comment]
This functionality has now been moved to a separate project and the remove cooldown option is no longer available.
